// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaAWY33Nyc2X3_QbdK1f0AZfLVrEW9noA',
    appId: '1:228566530405:web:b166d6b40f495fca8d098c',
    messagingSenderId: '228566530405',
    projectId: 'food-runner-26a14',
    authDomain: 'food-runner-26a14.firebaseapp.com',
    storageBucket: 'food-runner-26a14.firebasestorage.app',
    measurementId: 'G-5NMG631XDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0glHZHuBg4xiklmGF2wdAcD75zF-N1pY',
    appId: '1:228566530405:android:d84ab1bcf6f8e4368d098c',
    messagingSenderId: '228566530405',
    projectId: 'food-runner-26a14',
    storageBucket: 'food-runner-26a14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs7EZB-W1HvFcaTp6XejTmngSKnWCZeTg',
    appId: '1:228566530405:ios:36783b557403416e8d098c',
    messagingSenderId: '228566530405',
    projectId: 'food-runner-26a14',
    storageBucket: 'food-runner-26a14.firebasestorage.app',
    iosBundleId: 'com.example.foodRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs7EZB-W1HvFcaTp6XejTmngSKnWCZeTg',
    appId: '1:228566530405:ios:36783b557403416e8d098c',
    messagingSenderId: '228566530405',
    projectId: 'food-runner-26a14',
    storageBucket: 'food-runner-26a14.firebasestorage.app',
    iosBundleId: 'com.example.foodRunner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaAWY33Nyc2X3_QbdK1f0AZfLVrEW9noA',
    appId: '1:228566530405:web:36543ec3f09940258d098c',
    messagingSenderId: '228566530405',
    projectId: 'food-runner-26a14',
    authDomain: 'food-runner-26a14.firebaseapp.com',
    storageBucket: 'food-runner-26a14.firebasestorage.app',
    measurementId: 'G-QHL2M0334W',
  );
}
